import type { Metadata } from 'next'
import './globals.css'

import { Inter } from 'next/font/google'
import Head from 'next/head'

import Navbar from '@/components/internal/navbar'
import { ApolloWrapper } from '@/components/internal/wrapper/apollo'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <Head>
                <title>Star Dust - Cloud Deployment Platform</title>
            </Head>
            <body className={inter.className}>
                <ApolloWrapper>
                    <Navbar />
                    {children}
                </ApolloWrapper>
            </body>
        </html>
    )
}
